/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.irt.scom;

import java.awt.Color;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.Timestamp;
import javax.swing.JTextPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Csaba Lénárt
 */
public class LogWin extends javax.swing.JDialog {

    /**
     * Creates new form LogWin
     */
    public LogWin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void logError(String text){
	StyledDocument doc = logWin.getStyledDocument();
	SimpleAttributeSet red = new SimpleAttributeSet();
	SimpleAttributeSet normal = new SimpleAttributeSet();
	SimpleAttributeSet light = new SimpleAttributeSet();
	StyleConstants.setForeground(red, Color.RED);
	StyleConstants.setForeground(normal, Color.black);
	StyleConstants.setForeground(light, Color.GRAY);
	try
	{
	    doc.insertString(doc.getLength(), "\n[ERROR]", red );
	    doc.insertString(doc.getLength(), getTimestamp(), light );
	    doc.insertString(doc.getLength(), text==null?"":text, normal );
	}
	    catch(Exception e) { System.out.println(e); 
	}
    }
    public void logDebug(String text){
	StyledDocument doc = logWin.getStyledDocument();
	SimpleAttributeSet red = new SimpleAttributeSet();
	SimpleAttributeSet normal = new SimpleAttributeSet();
	SimpleAttributeSet light = new SimpleAttributeSet();
	StyleConstants.setForeground(red, new Color(0,100,0));
	StyleConstants.setForeground(normal, Color.black);
	StyleConstants.setForeground(light, Color.GRAY);
	try
	{
	    doc.insertString(doc.getLength(), "\n[DEBUG]", red );
	    doc.insertString(doc.getLength(), getTimestamp(), light );
	    doc.insertString(doc.getLength(), text==null?"":text, normal );
	}
	    catch(Exception e) { System.out.println(e); 
	}
	
    }
    public void logWarning(String text){
	StyledDocument doc = logWin.getStyledDocument();
	SimpleAttributeSet red = new SimpleAttributeSet();
	SimpleAttributeSet normal = new SimpleAttributeSet();
	SimpleAttributeSet light = new SimpleAttributeSet();
	StyleConstants.setForeground(red, Color.orange);
	StyleConstants.setForeground(normal, Color.black);
	StyleConstants.setForeground(light, Color.GRAY);
	try
	{
	    doc.insertString(doc.getLength(), "\n[WARN ]", red );
	    doc.insertString(doc.getLength(), getTimestamp(), light );
	    doc.insertString(doc.getLength(), text==null?"":text, normal );
	}
	    catch(Exception e) { System.out.println(e); 
	}
    }
    public void logInfo(String text){
	StyledDocument doc = logWin.getStyledDocument();
	SimpleAttributeSet red = new SimpleAttributeSet();
	SimpleAttributeSet normal = new SimpleAttributeSet();
	SimpleAttributeSet light = new SimpleAttributeSet();
	StyleConstants.setForeground(red, Color.BLUE);
	StyleConstants.setForeground(normal, Color.black);
	StyleConstants.setForeground(light, Color.GRAY);
	try
	{
	    doc.insertString(doc.getLength(), "\n[INFO ]", red );
	    doc.insertString(doc.getLength(), getTimestamp(), light );
	    doc.insertString(doc.getLength(), text==null?"":text, normal );
	}
	    catch(Exception e) { System.out.println(e); 
	}
    }
    
    public void logException(String message,Exception ex){
	StyledDocument doc = logWin.getStyledDocument();
	SimpleAttributeSet red = new SimpleAttributeSet();
	SimpleAttributeSet normal = new SimpleAttributeSet();
	SimpleAttributeSet light = new SimpleAttributeSet();
	SimpleAttributeSet gray = new SimpleAttributeSet();
	StyleConstants.setForeground(red, Color.RED);
	StyleConstants.setForeground(normal, Color.black);
	StyleConstants.setForeground(light, Color.GRAY);
	StyleConstants.setForeground(gray, new Color(150,0,0));
	try
	{
	    doc.insertString(doc.getLength(), "\n[ERROR]", red );
	    doc.insertString(doc.getLength(), getTimestamp(), light );
	    doc.insertString(doc.getLength(), message==null?"":message, normal );
	    if(ex!=null){
		StringWriter sw = new StringWriter();
		PrintWriter pw = new PrintWriter(sw);
		ex.printStackTrace(pw);
		String sStackTrace = sw.toString();
		doc.insertString(doc.getLength(), "\n"+sStackTrace, gray);
	    }
	}
	    catch(Exception e) { System.out.println(e); 
	}
    }
    
    public String getTimestamp(){
	return "["+new Timestamp(System.currentTimeMillis()).toString()+"] ";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logScroll = new javax.swing.JScrollPane();
        logWin = new JTextPane() {
            @Override
            public boolean getScrollableTracksViewportWidth() {
                return getUI().getPreferredSize(this).width
                <= getParent().getSize().width;
            }

        };
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Logs");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        logWin.setEditable(false);
        logWin.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        logWin.setText("************************************************\n***       Welcome to IRT SerCom Console      ***\n************************************************");
        logScroll.setViewportView(logWin);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        logWin.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LogWin dialog = new LogWin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane logScroll;
    private javax.swing.JTextPane logWin;
    // End of variables declaration//GEN-END:variables
}
